### PR TITLE
update shared partials

### PR DESCRIPTION
**Pull request by mojavelinux**
- add task to update shared partials (update-shared-partials)
- remove formatting from shared partials
- use shared partials from https://developer.mulesoft.com
- update styles to work with HTML from developer.mulesoft.com endpoint
- move shared partials into dedicated files
- include shared partials from header.hbs and footer.hbs, respectively
- move footer scripts into footer-scripts.hbs
- switch to MuleSoft dev logo; slighly increase size
- use consistent spacing in Handlebars expressions

### CODE REVIEW

**Comment by mojavelinux** [comment]
Switching from the footer from mulesoft.com to the footer from developer.mulesoft.com breaks some of the footer styles. We should be aligning with developer.mulesoft.com, though I need to confirm that.

**Comment by mojavelinux** [comment]
The new tasks automatically downloads the shared partials from the endpoint. We can make automated modifications to these files, but we should not be formatting them (unless that is also automated). However, I think by not formatting them, it makes it easier to manually examine the changes if and when that is necessary.

**Comment by hsablonniere** [comment]
Before we merge this, there are still a few issues to attend:

* We lack a wrapper around `.footer-end` to apply the narrow page with the different background color
  * Should we even have a narrow version of the footer for the docs? It's looks strange
* I don't know where to find some of the rounded icons
* Should we have the MuleSoft//Dev logo or the just MuleSoft logo?
* Can we see a usage of these endpoints?
  * The footer from developer.mulesoft.com is different
* They changed the URL in links to some .io domain

**Comment by hsablonniere** [comment]
I fixed a few stuffs so it looks like developer.mulesoft.com ;-)

**Comment by mojavelinux** [comment]
Thanks @hsablonniere!

I know the replacements in the gulp task look really ugly. But, to be honest, the only reason they exist is because what we're being given is broken. So it could be viewed as a wishlist for what needs to be fixed upstream.

**Pull request merged**
